# -*- coding: utf-8 -*-
"""
Maestro YAML 流生成器。

将内部 FlowStep[] DSL 转换为 Maestro 兼容的 YAML 格式。

关键映射：
  FlowStep → Maestro YAML 指令
  launch_app    → - launchApp: "com.example.app"
  stop_app      → - stopApp: com.example.app
  tap           → - tapOn: "登录"  /  - tapOn: id=xxx
  input         → - inputText: "hello"
  swipe         → - swipe:
                      direction: UP
  scroll        → - scroll
  assert        → - assertVisible: "首页"  /  - assertNotVisible: "..."
  wait          → - extendedWaitUntil:
                      visible: "加载完成"
                      timeout: 10000
  screenshot    → - takeScreenshot: step_3
  back          → - pressKey: back
  long_press    → - longPressOn: "长按区域"

额外自动注入：
  - appId: <package>
  - 通用系统弹窗处理模板
  - 全局超时 / 重试配置
"""

from __future__ import annotations

import textwrap
import yaml as _yaml_module  # type: ignore
from typing import Dict, List, Optional

from mobile_engine.engine_interface import (
    DeviceInfo,
    FlowStep,
    LocatorInfo,
    LocatorStrategy,
)

try:
    from uat_logger import uat_logger
except ImportError:
    import logging

    uat_logger = logging.getLogger(__name__)

# Try to use the system yaml, fallback to simple dict-to-yaml conversion
try:
    import yaml as _yaml
except ImportError:
    _yaml = None


class MaestroFlowGenerator:
    """将 FlowStep[] 转换为 Maestro YAML 内容"""

    # ------------------------------------------------------------------
    # YAML 模板
    # ------------------------------------------------------------------

    # Maestro YAML 头部模板
    HEADER_TEMPLATE = textwrap.dedent("""\
    # Generated by Testory Maestro Engine
    # {description}
    appId: {app_package}
    ---
    """)

    # 系统弹窗自动处理 (Maestro 1.x+ 格式)
    SYSTEM_DIALOG_HANDLER = textwrap.dedent("""\
    # --- 自动注入: 系统弹窗处理 ---
    - runFlow:
        when:
          visible:
            text: "允许"
        commands:
          - tapOn: "允许"
    - runFlow:
        when:
          visible:
            text: "确定"
        commands:
          - tapOn: "确定"
    - runFlow:
        when:
          visible:
            text: "始终允许"
        commands:
          - tapOn: "始终允许"
    ---
    """)

    # 权限弹窗处理
    PERMISSION_DIALOG_HANDLER = textwrap.dedent("""\
    # --- 自动注入: 权限弹窗处理 ---
    - runFlow:
        when:
          visible:
            id: "com.android.permissioncontroller:id/permission_allow_button"
        commands:
          - tapOn:
              id: "com.android.permissioncontroller:id/permission_allow_button"
    - runFlow:
        when:
          visible:
            text: "While using the app"
        commands:
          - tapOn: "While using the app"
    - runFlow:
        when:
          visible:
            text: "仅在使用中允许"
        commands:
          - tapOn: "仅在使用中允许"
    ---
    """)

    # ------------------------------------------------------------------
    # 公开 API
    # ------------------------------------------------------------------

    def generate(
        self,
        steps: List[FlowStep],
        *,
        device: Optional[DeviceInfo] = None,
        app_package: str = "",
        flow_name: str = "",
        inject_dialogs: bool = True,
    ) -> str:
        """
        生成完整 Maestro YAML 字符串。

        Args:
            steps: 流程步骤列表
            device: 设备信息 (提取 app_package)
            app_package: 目标 app 包名 (优先级高于 device.app_package)
            flow_name: 流程描述名称
            inject_dialogs: 是否注入系统弹窗处理
        """
        pkg = app_package or (device.app_package if device else "")
        if not pkg and steps:
            # 尝试从第一个 launch_app 步骤提取
            for s in steps:
                if s.action == "launch_app" and s.input_value:
                    pkg = s.input_value
                    break

        lines: List[str] = []

        # YAML 头部
        desc = flow_name or "Maestro Test Flow"
        lines.append(self.HEADER_TEMPLATE.format(
            description=desc,
            app_package=pkg or "com.example.app",
        ))

        # 注入系统弹窗处理
        if inject_dialogs:
            from mobile_env_config import maestro_auto_inject_dialogs

            if maestro_auto_inject_dialogs():
                lines.append(self.SYSTEM_DIALOG_HANDLER)
                lines.append(self.PERMISSION_DIALOG_HANDLER)

        # 全局配置 (Maestro 2.x)
        lines.append(textwrap.dedent("""\
        # --- 全局配置 ---
        - extendedWaitUntil:
            visible:
              anyOf:
                - text: ".*"
            timeout: 15000
        ---
        """))

        # 步骤转换
        for i, step in enumerate(steps):
            yaml_block = self.step_to_yaml(step, index=i)
            if yaml_block:
                lines.append(yaml_block)

        return "\n".join(lines)

    def step_to_yaml(self, step: FlowStep, index: int = 0) -> str:
        """单个步骤 → Maestro YAML 指令块"""
        action = step.action.strip().lower()
        label = step.maestro_label or f"step_{index}_{action}"

        lines: List[str] = [f"# [{label}] {step.description or action}"]

        try:
            if action == "launch_app":
                lines.append(self._launch_app(step))
            elif action == "stop_app":
                lines.append(self._stop_app(step))
            elif action == "tap":
                lines.append(self._tap(step))
            elif action == "long_press":
                lines.append(self._long_press(step))
            elif action in ("input", "input_text"):
                lines.append(self._input_text(step))
            elif action == "swipe":
                lines.append(self._swipe(step))
            elif action == "scroll":
                lines.append(self._scroll(step))
            elif action in ("assert", "assert_element"):
                lines.append(self._assert(step))
            elif action == "wait":
                lines.append(self._wait(step))
            elif action == "screenshot":
                lines.append(self._screenshot(step))
            elif action == "back":
                lines.append(self._back(step))
            elif action == "press_key":
                lines.append(self._press_key(step))
            else:
                uat_logger.warning("未知 action: %s，跳过", action)
                return ""
        except Exception as exc:
            uat_logger.error("步骤 %d 转 YAML 失败: %s", index, exc)
            lines.append(f"# ERROR: {exc}")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # 各 action 转换方法
    # ------------------------------------------------------------------

    def _launch_app(self, step: FlowStep) -> str:
        pkg = step.input_value or ""
        activity = ""
        if step.locator and step.locator.value:
            activity = step.locator.value
        if activity:
            return f'- launchApp:\n    appId: "{pkg}"\n    activity: "{activity}"'
        else:
            return f'- launchApp: "{pkg}"'

    def _stop_app(self, step: FlowStep) -> str:
        pkg = step.input_value or ""
        return f'- stopApp: "{pkg}"'

    def _tap(self, step: FlowStep) -> str:
        if step.tap_x is not None and step.tap_y is not None:
            return f"- tapOn:\n    point: \"{step.tap_x}%,{step.tap_y}%\""
        if step.locator:
            selector = self.locator_to_maestro(step.locator)
            optional = "optional: true" if step.maestro_optional else ""
            retry = ""
            if step.maestro_retry > 0:
                retry = f"retry: {step.maestro_retry}"
            parts = [f"- tapOn: {selector}"]
            if optional:
                parts.append(f"    {optional}")
            if retry:
                parts.append(f"    {retry}")
            return "\n".join(parts)
        return "- tapOn: # 无定位符"

    def _long_press(self, step: FlowStep) -> str:
        if step.locator:
            selector = self.locator_to_maestro(step.locator)
            return f"- longPressOn: {selector}"
        return "- longPressOn: # 无定位符"

    def _input_text(self, step: FlowStep) -> str:
        text = step.input_value or ""
        # 需要转义特殊字符
        safe_text = text.replace('"', '\\"')
        return f'- inputText: "{safe_text}"'

    def _swipe(self, step: FlowStep) -> str:
        direction = step.swipe_direction.upper() or "UP"
        duration = step.swipe_duration_ms or 400
        if step.swipe_start and step.swipe_end:
            # 自定义起止点
            return (
                f"- swipe:\n"
                f'    start: "{step.swipe_start}"\n'
                f'    end: "{step.swipe_end}"\n'
                f"    duration: {duration}"
            )
        else:
            return f"- swipe:\n    direction: {direction}\n    duration: {duration}"

    def _scroll(self, step: FlowStep) -> str:
        direction = step.swipe_direction.upper() or "DOWN"
        if direction in ("UP", "DOWN"):
            return f"- scroll:\n    direction: {direction}"
        # Maestro scroll 仅支持 UP/DOWN
        return "- scroll"

    def _assert(self, step: FlowStep) -> str:
        condition = step.assert_type or "visible"
        if step.locator:
            selector = self.locator_to_maestro(step.locator)
            if condition == "not_visible":
                return f"- assertNotVisible: {selector}"
            elif condition == "contains_text":
                # 通过文本包含断言
                return f"- assertVisible:\n    text: \"{step.locator.value}\""
            else:
                return f"- assertVisible: {selector}"
        return f"- assertVisible: # 无定位符"

    def _wait(self, step: FlowStep) -> str:
        timeout = step.wait_timeout_ms or 10000
        if step.locator:
            selector = self.locator_to_maestro(step.locator)
            return (
                f"- extendedWaitUntil:\n"
                f"    visible: {selector}\n"
                f"    timeout: {timeout}"
            )
        # 简单等待
        return f"- extendedWaitUntil:\n    visible:\n      text: \".*\"\n    timeout: {timeout}"

    def _screenshot(self, step: FlowStep) -> str:
        label = step.maestro_label or f"screenshot"
        safe_label = label.replace(" ", "_").replace('"', '').replace("'", "")
        return f'- takeScreenshot: {safe_label}'

    def _back(self, step: FlowStep) -> str:
        return "- back"

    def _press_key(self, step: FlowStep) -> str:
        key = step.input_value or "back"
        return f'- pressKey: {key}'

    # ------------------------------------------------------------------
    # 定位符转换
    # ------------------------------------------------------------------

    def locator_to_maestro(self, locator: LocatorInfo) -> str:
        """将 LocatorInfo 转为 Maestro 选择器字符串"""
        strategy = locator.strategy

        if strategy == LocatorStrategy.TEXT:
            val = locator.value.replace('"', '\\"')
            return f'"{val}"'

        elif strategy == LocatorStrategy.ID:
            return locator.value

        elif strategy == LocatorStrategy.ACCESSIBILITY_ID:
            return locator.value

        elif strategy == LocatorStrategy.SEMANTIC:
            # Maestro AI: 直接用语义描述
            val = locator.semantic_desc or locator.value
            val = val.replace('"', '\\"')
            return f'"{val}"'

        elif strategy == LocatorStrategy.RELATIVE:
            direction = locator.relative_direction
            target = locator.relative_target
            if direction == "below":
                return f'below "{target}"'
            elif direction == "rightOf":
                return f'rightOf "{target}"'
            elif direction == "above":
                return f'above "{target}"'
            elif direction == "leftOf":
                return f'leftOf "{target}"'
            return f'"{target}"'

        elif strategy == LocatorStrategy.VISUAL:
            # 坐标模式 (百分比)
            return f'"{locator.value}"'

        elif strategy == LocatorStrategy.COORDINATE:
            # 例如 "50%,30%"
            return f'point: {locator.value}'

        else:
            # 默认作为文本处理
            val = locator.value.replace('"', '\\"')
            return f'"{val}"'

    # ------------------------------------------------------------------
    # 便捷方法
    # ------------------------------------------------------------------

    def generate_to_file(
        self,
        steps: List[FlowStep],
        output_path: str,
        **kwargs,
    ) -> str:
        """生成 YAML 并写入文件，返回文件路径"""
        content = self.generate(steps, **kwargs)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        return output_path

    def generate_db_steps_to_yaml(
        self,
        db_steps: List[dict],
        **kwargs,
    ) -> str:
        """将数据库步骤 dict 转换为 Maestro YAML"""
        flow_steps = self._convert_db_steps(db_steps)
        return self.generate(flow_steps, **kwargs)

    @staticmethod
    def _convert_db_steps(db_steps: List[dict]) -> List[FlowStep]:
        """将数据库 test_steps 记录转换为 FlowStep 列表"""
        results = []
        for s in db_steps:
            action = (s.get("action") or "").strip().lower()
            # 别名映射
            alias_map = {
                "click": "tap",
                "fill": "input",
                "open_app": "launch_app",
                "close_app": "stop_app",
                "verify": "assert",
                "assert_text": "assert",
            }
            mapped_action = alias_map.get(action, action)

            locator = None
            sel_type = (s.get("selector_type") or "").strip()
            sel_value = (s.get("selector_value") or "").strip()
            if sel_value:
                strat = LocatorStrategy.ACCESSIBILITY_ID
                if sel_type in ("text", "name"):
                    strat = LocatorStrategy.TEXT
                elif sel_type in ("id", "css"):
                    strat = LocatorStrategy.ID
                elif sel_type in ("xpath",):
                    strat = LocatorStrategy.SEMANTIC  # XPath → AI 语义匹配
                elif sel_type in ("visual", "visual_template"):
                    strat = LocatorStrategy.VISUAL
                locator = LocatorInfo(
                    strategy=strat,
                    value=sel_value,
                    semantic_desc=s.get("description", ""),
                )

            fs = FlowStep(
                action=mapped_action,
                description=s.get("description", ""),
                locator=locator,
                input_value=(s.get("input_value") or ""),
                swipe_direction=s.get("swipe_x", ""),
                swipe_duration_ms=400,
                assert_type=s.get("compare_type", "visible"),
                wait_timeout_ms=s.get("wait_timeout_ms", 10000),
                maestro_label=s.get("maestro_label", ""),
                maestro_optional=bool(s.get("maestro_optional", False)),
                maestro_retry=int(s.get("maestro_retry", 0)),
            )
            results.append(fs)
        return results
